### PR TITLE
more boilerplate: fix DISCLAIMER; add CONTRIBUTING

### PR DESCRIPTION
**Pull request by dgrove-oss**

### CODE REVIEW

**Comment by rabbah** [comment]
can you fix the ibm mention in the README?

**Comment by dgrove-oss** [comment]
that's the name of the old NPM module.  The thought was to leave the npm module intact for a short time until we are get things configured to publish and @openwhisk/composer or @openwhisk-composer/composer (so the README doesn't point to a non-existent npm module).   I agree we need to do this quickly...

**Comment by tardieu** [comment]
I propose `openwhisk-composer` for the npm package name.

**Comment by dgrove-oss** [comment]
I changed the top-level header to Apache OpenWhisk composer and added a note that we will be releasing under a different npm module name soon.  @rabbah Good enough for now?

**Pull request merged**
